<?php
declare(strict_types=1);
use SnackQuest\App;use SnackQuest\Config;use SnackQuest\Database;use SnackQuest\Http\Request;use SnackQuest\Router;use SnackQuest\Services\AiInsightService;use SnackQuest\Services\BarcodeService;use SnackQuest\Services\GameService;use SnackQuest\Services\OpenFoodFactsService;use SnackQuest\Services\ProductService;use SnackQuest\Services\ShareService;use SnackQuest\Support\HttpClient;
$root=dirname(__DIR__);$db=$root.'/storage/test.sqlite';if(is_file($db))unlink($db);if(!is_dir($root.'/storage'))mkdir($root.'/storage',0770,true);putenv('SQ_CONFIG='.$root.'/tests/config.test.php');require $root.'/src/bootstrap.php';App::boot();
$sql=str_replace('{{prefix}}','sq_',file_get_contents($root.'/migrations/sqlite/001_init.sql'));$sql=preg_replace('/^\s*--.*$/m','',$sql);foreach(array_filter(array_map('trim',preg_split('/;\s*(?:\r?\n|$)/',$sql)))as$stmt)Database::pdo()->exec($stmt);
$tags=['genau-richtig'=>['Genau richtig','taste'],'knusprig'=>['Knusprig','texture'],'filmabend'=>['Filmabend','context']];$up=Database::pdo()->prepare('INSERT INTO sq_taste_tags(slug,label,category)VALUES(:s,:l,:c)');foreach($tags as$s=>$v)$up->execute(['s'=>$s,'l'=>$v[0],'c'=>$v[1]]);
$passed=0;$failed=0;$test=function(string$name,callable$fn)use(&$passed,&$failed){try{$fn();echo"PASS {$name}\n";$passed++;}catch(Throwable$e){echo"FAIL {$name}: {$e->getMessage()}\n";$failed++;}};$assert=function(bool$ok,string$msg='assertion failed'){if(!$ok)throw new RuntimeException($msg);};
$test('EAN-13 checksum',fn()=>$assert(BarcodeService::validate('4006381333931')));$test('EAN-8 checksum',fn()=>$assert(BarcodeService::validate('96385074')));$test('UPC-A checksum',fn()=>$assert(BarcodeService::validate('036000291452')));$test('invalid checksum rejected',fn()=>$assert(!BarcodeService::validate('4006381333932')));
$router=new Router();$headHandler=[stdClass::class,'head'];$router->get('/head-check',$headHandler);$headMatch=$router->match(new Request('HEAD','/head-check',[],[],[]));$test('HEAD reuses GET routes',fn()=>$assert($headMatch!==null&&$headMatch[0]===$headHandler));
$http=new class implements HttpClient{public function request(string$m,string$u,array$h=[],?string$b=null,int$t=8):array{return['status'=>200,'body'=>'{}','error'=>null];}};$off=new OpenFoodFactsService(App::$config,App::$log,$http);$norm=$off->normalize('4006381333931',['product_name_de'=>'Test Chips','brands'=>'Echtmarke','nutriments'=>['salt_100g'=>1.2]],'https://world.openfoodfacts.org/product/4006381333931');$test('OFF normalization',fn()=>$assert($norm['name']==='Test Chips'&&$norm['key']==='off:4006381333931'&&$norm['nutriments']['salt_100g']===1.2));$missing=$off->normalize('96385074',[]);$test('OFF missing fields stay empty',fn()=>$assert($missing['brand']===null&&$missing['allergens']===null));
$now=gmdate('Y-m-d H:i:s');$users=Database::table('users');$ins=Database::pdo()->prepare("INSERT INTO {$users}(email,email_verified_at,password_hash,display_name,created_at,updated_at)VALUES(:e,:v,:p,:d,:c,:u)");foreach([['a@example.test','A'],['b@example.test','B']]as$row)$ins->execute(['e'=>$row[0],'v'=>$now,'p'=>password_hash('Password123',PASSWORD_DEFAULT),'d'=>$row[1],'c'=>$now,'u'=>$now]);$service=new ProductService();$p1=['key'=>'off:4006381333931','barcode'=>'4006381333931','name'=>'Test Chips','brand'=>'Echtmarke','categories'=>'Chips','image'=>''];$p2=['key'=>'off:036000291452','barcode'=>'036000291452','name'=>'Test Riegel','brand'=>'Echtmarke','categories'=>'Riegel','image'=>''];$p3=['key'=>'off:96385074','barcode'=>'96385074','name'=>'Test Cracker','brand'=>'Echtmarke','categories'=>'Cracker','image'=>''];$id1=$service->saveReview(1,$p1,['overall_rating'=>'9','buy_again'=>'yes','favorite'=>'1','tags'=>['knusprig']]);$service->saveReview(1,$p2,['overall_rating'=>'7','buy_again'=>'maybe','tags'=>['genau-richtig']]);$service->saveReview(1,$p3,['overall_rating'=>'8','buy_again'=>'yes','tags'=>['knusprig']]);$service->saveReview(2,$p1,['overall_rating'=>'2','buy_again'=>'no','tags'=>[]]);$test('ownership isolation',fn()=>$assert(count($service->list(1))===3&&count($service->list(2))===1&&$service->findEntry(2,$id1)===null));$test('rating validation',function()use($service,$p1,$assert){try{$service->saveReview(1,$p1,['overall_rating'=>11,'buy_again'=>'yes']);$assert(false);}catch(InvalidArgumentException){$assert(true);}});$profile=$service->tasteProfile(1);$test('taste profile uses real rows',fn()=>$assert($profile['count']===3&&$profile['average']===8.0));$game=new GameService($service);$battle=$game->nextBattle(1,'taste');$game->decide(1,$battle['session_id'],$battle['left']['product_key'],$battle['right']['product_key'],$battle['left']['product_key'],'taste');$test('Elo battle persisted',fn()=>$assert(count($game->rankings(1,'taste'))===2));
$prefs=Database::table('user_preferences');$prefInsert=Database::pdo()->prepare("INSERT INTO {$prefs}(user_id,ai_opt_in,analytics_opt_in,updated_at)VALUES(:u,1,0,:t)");$prefInsert->execute(['u'=>1,'t'=>$now]);$prefInsert->execute(['u'=>2,'t'=>$now]);
$aiConfig=Config::fromArray(['ai'=>['enabled'=>true,'base_url'=>'https://julian-neumann.org/api/openai.php/v1','api_key'=>'test-key','model'=>'local/test','timeout_seconds'=>2,'allowed_hosts'=>['julian-neumann.org']]]);
$aiHttp=new class implements HttpClient{public int$count=0;public string$body='';public function request(string$m,string$u,array$h=[],?string$b=null,int$t=8):array{$this->count++;$this->body=(string)$b;$content=json_encode(['summary'=>'Deine bisherigen Bewertungen zeigen eine klare Vorliebe für knusprige Snacks mit verlässlicher Wiederkaufstendenz.','discovery_idea'=>'Probiere als Nächstes vorsichtig eine andere knusprige Kategorie aus.'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);return['status'=>200,'body'=>json_encode(['choices'=>[['message'=>['content'=>$content]]]],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'error'=>null];}};$aiService=new AiInsightService($aiConfig,App::$log,$aiHttp);$aiResult=$aiService->generate(1,$profile);$test('AI insight accepts strict JSON and caches it',fn()=>$assert(str_contains($aiResult,'Entdeckungsidee:')&&$aiService->generate(1,$profile)===$aiResult&&$aiHttp->count===1));$test('AI payload excludes identity, notes and prices',function()use($aiHttp,$assert){$payload=json_decode($aiHttp->body,true);$sent=(string)($payload['messages'][1]['content']??'');$assert(!str_contains($sent,'a@example.test')&&!str_contains($sent,'Password123')&&!str_contains($sent,'price')&&!str_contains($sent,'note'));});
$asyncHttp=new class implements HttpClient{public int$count=0;public function request(string$m,string$u,array$h=[],?string$b=null,int$t=8):array{$this->count++;if($m==='POST')return['status'=>202,'body'=>json_encode(['result_url'=>'https://julian-neumann.org/api/v1/result.php?job_id=job_test_12345678']),'error'=>null];$content=json_encode(['summary'=>'Deine Bewertungen zeigen auch in dieser Auswertung ein klares, nachvollziehbares Geschmacksbild.','discovery_idea'=>'Vergleiche vorsichtig zwei ähnliche Snacks aus unterschiedlichen Kategorien.'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);return['status'=>200,'body'=>json_encode(['ok'=>true,'job'=>['status'=>'done'],'result'=>['summary'=>$content]],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'error'=>null];}};$asyncProfile=$profile;$asyncProfile['average']=7.9;$asyncAi=new AiInsightService($aiConfig,App::$log,$asyncHttp);$asyncResult=$asyncAi->generate(1,$asyncProfile);$test('AI insight follows a valid private async result URL',fn()=>$assert(str_contains($asyncResult,'Entdeckungsidee:')&&$asyncHttp->count===2));
$pendingHttp=new class implements HttpClient{public function request(string$m,string$u,array$h=[],?string$b=null,int$t=8):array{return['status'=>202,'body'=>'{}','error'=>null];}};$pendingAi=new AiInsightService($aiConfig,App::$log,$pendingHttp);$test('AI bridge 202 is rejected without storing content',function()use($pendingAi,$profile,$assert){try{$pendingAi->generate(2,$profile);$assert(false);}catch(RuntimeException$e){$assert(str_contains($e->getMessage(),'nicht erreichbar'));}});
$shares=new ShareService($service);$share=$shares->create(1,'review',$id1);$resolved=$shares->resolve($share['token']);$test('share snapshot excludes private note and identity',fn()=>$assert($resolved!==null&&!array_key_exists('note',$resolved['payload'])&&!array_key_exists('email',$resolved['payload'])));$test('share ownership protects revocation',fn()=>$assert(!$shares->revoke(2,$share['id'])&&$shares->revoke(1,$share['id'])&&$shares->resolve($share['token'])===null));
echo"\n{$passed} passed, {$failed} failed\n";exit($failed?1:0);
