-- SnackQuest 001_init (SQLite test dialect).
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS {{prefix}}users (id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT NOT NULL UNIQUE,email_verified_at TEXT,password_hash TEXT,google_sub TEXT UNIQUE,display_name TEXT NOT NULL DEFAULT '',avatar_url TEXT NOT NULL DEFAULT '',locale TEXT NOT NULL DEFAULT 'de',timezone TEXT NOT NULL DEFAULT 'Europe/Berlin',country TEXT NOT NULL DEFAULT 'DE',onboarding_completed INTEGER NOT NULL DEFAULT 0,is_active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS {{prefix}}auth_tokens (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL REFERENCES {{prefix}}users(id) ON DELETE CASCADE,token_type TEXT NOT NULL,token_hash TEXT NOT NULL,expires_at TEXT NOT NULL,used_at TEXT,created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_sq_auth_token ON {{prefix}}auth_tokens(token_type,token_hash);
CREATE TABLE IF NOT EXISTS {{prefix}}rate_limits (rl_key TEXT NOT NULL,window_start INTEGER NOT NULL,attempts INTEGER NOT NULL DEFAULT 1,PRIMARY KEY(rl_key,window_start));
CREATE TABLE IF NOT EXISTS {{prefix}}user_preferences (user_id INTEGER PRIMARY KEY REFERENCES {{prefix}}users(id) ON DELETE CASCADE,taste_preferences TEXT,favorite_categories TEXT,excluded_categories TEXT,default_sort TEXT NOT NULL DEFAULT 'recent',ai_opt_in INTEGER NOT NULL DEFAULT 0,analytics_opt_in INTEGER NOT NULL DEFAULT 0,notifications TEXT,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS {{prefix}}product_cache (barcode TEXT PRIMARY KEY,product_json TEXT,source_version TEXT NOT NULL DEFAULT 'v3.6',source_url TEXT NOT NULL DEFAULT '',source_updated_at TEXT,last_fetched_at TEXT NOT NULL,expires_at TEXT NOT NULL,fetch_status TEXT NOT NULL DEFAULT 'ok');
CREATE TABLE IF NOT EXISTS {{prefix}}custom_products (id INTEGER PRIMARY KEY AUTOINCREMENT,owner_user_id INTEGER NOT NULL REFERENCES {{prefix}}users(id) ON DELETE CASCADE,barcode TEXT,name TEXT NOT NULL,brand TEXT NOT NULL DEFAULT '',category TEXT NOT NULL DEFAULT '',quantity TEXT NOT NULL DEFAULT '',image_path TEXT NOT NULL DEFAULT '',note TEXT NOT NULL DEFAULT '',visibility TEXT NOT NULL DEFAULT 'private',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS {{prefix}}user_product_entries (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL REFERENCES {{prefix}}users(id) ON DELETE CASCADE,product_key TEXT NOT NULL,barcode TEXT,custom_product_id INTEGER REFERENCES {{prefix}}custom_products(id) ON DELETE SET NULL,product_name TEXT NOT NULL,brand TEXT NOT NULL DEFAULT '',category TEXT NOT NULL DEFAULT '',image_url TEXT NOT NULL DEFAULT '',overall_rating INTEGER NOT NULL,taste_rating INTEGER,texture_rating INTEGER,value_rating INTEGER,packaging_rating INTEGER,portion_rating INTEGER,buy_again TEXT NOT NULL DEFAULT 'maybe',favorite INTEGER NOT NULL DEFAULT 0,never_again INTEGER NOT NULL DEFAULT 0,movie_night INTEGER NOT NULL DEFAULT 0,note TEXT NOT NULL DEFAULT '',first_tried_at TEXT NOT NULL,last_tried_at TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(user_id,product_key));
CREATE TABLE IF NOT EXISTS {{prefix}}taste_tags (id INTEGER PRIMARY KEY AUTOINCREMENT,slug TEXT NOT NULL UNIQUE,label TEXT NOT NULL,category TEXT NOT NULL DEFAULT 'taste');
CREATE TABLE IF NOT EXISTS {{prefix}}user_product_tags (entry_id INTEGER NOT NULL REFERENCES {{prefix}}user_product_entries(id) ON DELETE CASCADE,tag_id INTEGER NOT NULL REFERENCES {{prefix}}taste_tags(id) ON DELETE CASCADE,PRIMARY KEY(entry_id,tag_id));
CREATE TABLE IF NOT EXISTS {{prefix}}stores (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL REFERENCES {{prefix}}users(id) ON DELETE CASCADE,name TEXT NOT NULL,city TEXT NOT NULL DEFAULT '',country TEXT NOT NULL DEFAULT 'DE',created_at TEXT NOT NULL,UNIQUE(user_id,name,city));
CREATE TABLE IF NOT EXISTS {{prefix}}price_entries (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL REFERENCES {{prefix}}users(id) ON DELETE CASCADE,product_key TEXT NOT NULL,price REAL NOT NULL,currency TEXT NOT NULL DEFAULT 'EUR',quantity_text TEXT NOT NULL DEFAULT '',store_id INTEGER REFERENCES {{prefix}}stores(id) ON DELETE SET NULL,store_name_snapshot TEXT NOT NULL DEFAULT '',purchased_at TEXT NOT NULL,receipt_photo_path TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS {{prefix}}review_photos (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL REFERENCES {{prefix}}users(id) ON DELETE CASCADE,entry_id INTEGER NOT NULL REFERENCES {{prefix}}user_product_entries(id) ON DELETE CASCADE,storage_path TEXT NOT NULL,width INTEGER NOT NULL DEFAULT 0,height INTEGER NOT NULL DEFAULT 0,mime_type TEXT NOT NULL,alt_text TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS {{prefix}}collections (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL REFERENCES {{prefix}}users(id) ON DELETE CASCADE,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',visibility TEXT NOT NULL DEFAULT 'private',share_token_hash TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS {{prefix}}collection_items (id INTEGER PRIMARY KEY AUTOINCREMENT,collection_id INTEGER NOT NULL REFERENCES {{prefix}}collections(id) ON DELETE CASCADE,product_key TEXT NOT NULL,product_name TEXT NOT NULL,image_url TEXT NOT NULL DEFAULT '',position INTEGER NOT NULL DEFAULT 0,added_at TEXT NOT NULL,UNIQUE(collection_id,product_key));
CREATE TABLE IF NOT EXISTS {{prefix}}battle_sessions (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL REFERENCES {{prefix}}users(id) ON DELETE CASCADE,battle_type TEXT NOT NULL DEFAULT 'taste',status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL,completed_at TEXT);
CREATE TABLE IF NOT EXISTS {{prefix}}battle_pairs (id INTEGER PRIMARY KEY AUTOINCREMENT,battle_session_id INTEGER NOT NULL REFERENCES {{prefix}}battle_sessions(id) ON DELETE CASCADE,left_product_key TEXT NOT NULL,right_product_key TEXT NOT NULL,winner_product_key TEXT,selection_reason TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS {{prefix}}ranking_scores (user_id INTEGER NOT NULL REFERENCES {{prefix}}users(id) ON DELETE CASCADE,product_key TEXT NOT NULL,dimension TEXT NOT NULL,score REAL NOT NULL DEFAULT 1000,match_count INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL,PRIMARY KEY(user_id,product_key,dimension));
CREATE TABLE IF NOT EXISTS {{prefix}}quests (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL REFERENCES {{prefix}}users(id) ON DELETE CASCADE,quest_type TEXT NOT NULL,title TEXT NOT NULL,parameters TEXT,status TEXT NOT NULL DEFAULT 'active',progress INTEGER NOT NULL DEFAULT 0,target INTEGER NOT NULL DEFAULT 1,starts_at TEXT NOT NULL,ends_at TEXT,completed_at TEXT);
CREATE TABLE IF NOT EXISTS {{prefix}}shares (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL REFERENCES {{prefix}}users(id) ON DELETE CASCADE,share_type TEXT NOT NULL,resource_id INTEGER NOT NULL,token_hash TEXT NOT NULL UNIQUE,payload TEXT NOT NULL,created_at TEXT NOT NULL,revoked_at TEXT);
CREATE TABLE IF NOT EXISTS {{prefix}}ai_insights (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL REFERENCES {{prefix}}users(id) ON DELETE CASCADE,insight_type TEXT NOT NULL,structured_input_hash TEXT NOT NULL,result TEXT NOT NULL,model TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,expires_at TEXT);
CREATE TABLE IF NOT EXISTS {{prefix}}audit_events (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER REFERENCES {{prefix}}users(id) ON DELETE SET NULL,event_type TEXT NOT NULL,request_id TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS {{prefix}}settings (s_key TEXT PRIMARY KEY,s_value TEXT NOT NULL,updated_at TEXT NOT NULL);

