<?php
$title=$title??'SnackQuest';
$flashes=$flashes??[];
$user=$currentUser??[];
$requestPath=(string)(parse_url((string)($_SERVER['REQUEST_URI']??''),PHP_URL_PATH)?:'');
$base=\SnackQuest\Support\View::$basePath;
$currentPath=$base!==''&&str_starts_with($requestPath,$base)?substr($requestPath,strlen($base)):$requestPath;
$navCurrent=static function(array $paths)use($currentPath):bool{
  foreach($paths as $path){
    if($currentPath===$path||($path!=='/app'&&str_starts_with($currentPath,$path.'/')))return true;
  }
  return false;
};
?>
<!doctype html>
<html lang="de">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#fffdf5"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><meta name="apple-mobile-web-app-title" content="SnackQuest"><meta name="robots" content="noindex,nofollow"><title><?=e($title)?></title>
  <link rel="manifest" href="<?=u('/manifest.webmanifest')?>?v=<?=e(\SnackQuest\Support\View::$appVersion)?>"><link rel="icon" href="<?=u('/assets/icons/favicon-v2-32.png')?>" sizes="32x32" type="image/png"><link rel="icon" href="<?=u('/assets/icons/favicon-v2-64.png')?>" sizes="64x64" type="image/png"><link rel="apple-touch-icon" href="<?=u('/assets/icons/icon-v2-180.png')?>" sizes="180x180"><link rel="stylesheet" href="<?=u('/assets/css/app.css')?>?v=<?=e(\SnackQuest\Support\View::$appVersion)?>">
  <script defer src="<?=u('/assets/js/app.js')?>?v=<?=e(\SnackQuest\Support\View::$appVersion)?>"></script><script defer src="<?=u('/assets/js/share.js')?>?v=<?=e(\SnackQuest\Support\View::$appVersion)?>"></script>
</head>
<body class="app-body" data-user-id="<?=e((string)($user['id']??''))?>" data-clear-review-draft="<?=e((string)($clearReviewDraft??''))?>" data-clear-review-before="<?=e((string)($clearReviewBefore??0))?>"><a class="skip-link" href="#main">Zum Inhalt springen</a><header class="app-header"><a class="brand brand-compact" href="<?=u('/app')?>" aria-label="SnackQuest Übersicht"><?php include __DIR__.'/../partials/logo.php';?></a><div class="app-user"><span><?=e($user['display_name']??'')?></span><form method="post" action="<?=u('/logout')?>"><?=$csrf??''?><button class="link-button" type="submit">Abmelden</button><span class="logout-status" data-logout-status role="status" aria-live="polite"></span></form></div></header>
<aside class="side-nav" aria-label="App-Navigation"><a class="<?=$navCurrent(['/app'])?'is-current':''?>" <?=$navCurrent(['/app'])?'aria-current="page"':''?> href="<?=u('/app')?>">Übersicht</a><a class="<?=$navCurrent(['/app/scan'])?'is-current':''?>" <?=$navCurrent(['/app/scan'])?'aria-current="page"':''?> href="<?=u('/app/scan')?>">Scannen</a><a class="<?=$navCurrent(['/app/library','/app/favorites','/app/buy-again','/app/never-again','/app/entry','/app/product','/app/custom'])?'is-current':''?>" <?=$navCurrent(['/app/library','/app/favorites','/app/buy-again','/app/never-again','/app/entry','/app/product','/app/custom'])?'aria-current="page"':''?> href="<?=u('/app/library')?>">Bibliothek</a><a class="<?=$navCurrent(['/app/collections'])?'is-current':''?>" <?=$navCurrent(['/app/collections'])?'aria-current="page"':''?> href="<?=u('/app/collections')?>">Sammlungen</a><a class="<?=$navCurrent(['/app/battles'])?'is-current':''?>" <?=$navCurrent(['/app/battles'])?'aria-current="page"':''?> href="<?=u('/app/battles')?>">Duelle</a><a class="<?=$navCurrent(['/app/quests'])?'is-current':''?>" <?=$navCurrent(['/app/quests'])?'aria-current="page"':''?> href="<?=u('/app/quests')?>">Quests</a><a class="<?=$navCurrent(['/app/taste-profile'])?'is-current':''?>" <?=$navCurrent(['/app/taste-profile'])?'aria-current="page"':''?> href="<?=u('/app/taste-profile')?>">Geschmack</a><a class="<?=$navCurrent(['/app/settings','/app/account','/app/shares'])?'is-current':''?>" <?=$navCurrent(['/app/settings','/app/account','/app/shares'])?'aria-current="page"':''?> href="<?=u('/app/settings')?>">Einstellungen</a></aside>
<?php foreach($flashes as $flash):?><div class="flash flash-<?=e($flash['type']??'info')?>" role="status"><?=e($flash['text']??'')?></div><?php endforeach;?>
<main id="main" class="app-main"><?=$content?></main><nav class="bottom-nav" aria-label="Mobile App-Navigation"><a class="<?=$navCurrent(['/app'])?'is-current':''?>" <?=$navCurrent(['/app'])?'aria-current="page"':''?> href="<?=u('/app')?>"><span>⌂</span>Heute</a><a class="<?=$navCurrent(['/app/library','/app/favorites','/app/buy-again','/app/never-again','/app/entry','/app/product','/app/custom'])?'is-current':''?>" <?=$navCurrent(['/app/library','/app/favorites','/app/buy-again','/app/never-again','/app/entry','/app/product','/app/custom'])?'aria-current="page"':''?> href="<?=u('/app/library')?>"><span>▤</span>Bibliothek</a><a class="scan-tab <?=$navCurrent(['/app/scan'])?'is-current':''?>" <?=$navCurrent(['/app/scan'])?'aria-current="page"':''?> href="<?=u('/app/scan')?>" aria-label="Snack scannen"><span>▦</span>Scan</a><a class="<?=$navCurrent(['/app/battles'])?'is-current':''?>" <?=$navCurrent(['/app/battles'])?'aria-current="page"':''?> href="<?=u('/app/battles')?>"><span>⇄</span>Duelle</a><a class="<?=$navCurrent(['/app/taste-profile'])?'is-current':''?>" <?=$navCurrent(['/app/taste-profile'])?'aria-current="page"':''?> href="<?=u('/app/taste-profile')?>"><span>◎</span>Profil</a></nav></body></html>
